title: Nick Horton # your name (or website title) here
logo: "/images/0.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a recent graduate of <a href="https://www.thisismetis.com/">Metis</a>, an ACCET accredited 12 week immersive data science bootcamp focused on project
  oriented learning.
  <br><br>
  I am currently looking for a position as a data analyst.
  <br><br>
  <a href="https://www.linkedin.com/in/nicholaschorton/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-193770274-2 # your Google Analytics tracking ID here
